### ISSUE TITLE
Error: Expected [function execute] to be a GraphQL schema

### ISSUE THREAD

**Issue by Maxpain177** [instana/nodejs-sensor#170] opened 2019-10-02 20:12 UTC
Hi.
Thank you for awesome APM solution :)
We are using GraphQL schema stitching and got the error:

```
Error: Expected [function execute] to be a GraphQL schema.
  File "/app/node_modules/graphql/type/schema.js", line 41, col 11, in assertSchema
    throw new Error("Expected ".concat((0, _inspect.default)(schema), " to be a GraphQL schema."));
  File "/app/node_modules/graphql/type/validate.js", line 44, col 28, in validateSchema
    (0, _schema.assertSchema)(schema); // If this Schema has already been validated, return the previous results.
  File "/app/node_modules/graphql/type/validate.js", line 68, col 16, in assertValidSchema
    var errors = validateSchema(schema);
  File "/app/node_modules/graphql/execution/execute.js", line 136, col 35, in assertValidExecutionArguments
    (0, _validate.assertValidSchema)(schema); // Variables, if provided, must be an object.
  File "/app/node_modules/graphql/execution/execute.js", line 86, col 3, in executeImpl
    assertValidExecutionArguments(schema, document, variableValues); // If a valid execution context cannot be created due to incorrect arguments,
  File "/app/node_modules/graphql/execution/execute.js", line 64, col 63, in execute
    return arguments.length === 1 ? executeImpl(argsOrSchema) : executeImpl({
  File "/app/node_modules/@instana/core/src/tracing/instrumentation/protocols/graphql.js", line 128, col 31, in traceQueryOrMutation
    return originalFunction.apply(this, arguments);
  File "/app/node_modules/@instana/core/src/tracing/instrumentation/protocols/graphql.js", line 75, col 14, in Object.instrumentedExecute
    return traceQueryOrMutation(
  File "/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js", line 96, col 52, in null.<anonymous>
    return [4 /*yield*/, graphql_1.execute(options.schema, processedRequest.document, info.rootValue, options.context, proce {snip}
  File "/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js", line 31, col 23, in step
    op = body.call(thisArg, _);
```

**Comment by basti1302** [comment] 2019-10-04 09:54
Hi @Maxpain177 

thanks for reporting, I'll look into this as soon as possible.

**Comment by basti1302** [comment] 2019-10-11 14:08
Hi @Maxpain177 

version `@instana/collector@1.73.1` contains a fix for this breakage. You should be able to update to that version and that error should go away.

However, the code path indicates that even though this will no longer run into an error, it might not trace the call correctly. You should see something like 

```
Cannot start a GraphQL entry span when another span is already active. Currently, the following span is active: {.....}`
```

in your logs, followed by the details of the span that is already active. I would be interested what that is.

If you have time to test the new version, could you keep an eye open for those log statements and copy and paste some of them here?

Also, if possible, I would be interested in some code snippets that show how you have set up schema stitching so I might be able to reproduce this and include it in my test cases.

Thanks in advance!

**Comment by Maxpain177** [comment] 2019-10-11 15:52
@basti1302 hello.

After upgrade to the last version I get errors in the console:

```
Cannot start a GraphQL entry span when another span is already active. Currently, the following span is active: {"t":"f9b01a6eea67ea25","s":"773d2d68999d6067","n":"graphql.server","k":1,"f":{"e":"663015","h":"GCE-6254954720124921768"},"async":false,"error":false,"ec":0,"ts":1570808890324,"d":0,"stack":[{"m":"<anonymous>","c":"/app/node_modules/apollo-server-core/dist/requestPipeline.js","n":240},{"m":"Generator.next"},{"m":"<anonymous>","c":"/app/node_modules/apollo-server-core/dist/requestPipeline.js","n":8},{"m":"new Promise"},{"m":"__awaiter","c":"/app/node_modules/apollo-server-core/dist/requestPipeline.js","n":4},{"m":"execute","c":"/app/node_modules/apollo-server-core/dist/requestPipeline.js","n":219},{"m":"<anonymous>","c":"/app/node_modules/apollo-server-core/dist/requestPipeline.js","n":157},{"m":"Generator.next"},{"m":"fulfilled","c":"/app/node_modules/apollo-server-core/dist/requestPipeline.js","n":5},{"m":"process.processTicksAndRejections","c":"internal/process/task_queues.js","n":93}],"data":{"graphql":{"operationType":"query","operationName":"UserMatchesAggregateQuery","fields":{"match_members_aggregate":["aggregate","__typename"],"common_match_members_aggregate":["aggregate","__typename"]},"args":{"match_members_aggregate":["where"],"common_match_members_aggregate":["args","where"]}}}}" 
```

I can make a reproduction repo later.

**Comment by basti1302** [comment] 2019-10-14 06:57
Hi @Maxpain177,

that is interesting. If the already-active span is also a GraphQL call, I would expect the root GraphQL call to be visible in Instana but subsequent schema stitching calls to be missing. A reproduction repo would be a great help to improve this.

As far as I know, schema stitching is [deprecated](https://www.apollographql.com/docs/graphql-tools/schema-stitching/). Do you have plans to migrate away from schema stitching to [Apollo federation](https://www.apollographql.com/docs/apollo-server/federation/migrating-from-stitching/)?

**Comment by Maxpain177** [comment] 2019-10-14 07:02
@basti1302 we can't use the Federation because it doesn't support subscriptions.

**Comment by basti1302** [comment] 2019-10-25 07:11
I'll close this for now. If you are still missing spans due to this, please file a ticket at https://support.instana.com/hc/en-us/requests/new. If you can include a short reproduction, that would be great.

**Closed by basti1302** 2019-10-25 07:11 UTC
