### ISSUE TITLE
@instana/collector 1.119.0 does not find module '../../../../../core/src/tracing/cls'

### ISSUE THREAD

**Issue by michael42** [instana/nodejs-sensor#318] opened 2021-04-07 10:45 UTC
The recently released @instana/collector 1.119.0 does not work for us anymore (1.118.0 did work):

```shell
$ npm install --global --only=production @instana/collector@1.119.0
$ export NODE_PATH=$(npm root --quiet --global)
$ node -e 'require("@instana/collector")'
[...]
Error: Cannot find module '../../../../../core/src/tracing/cls'
Require stack:
- $HOME/.npm-global/lib/node_modules/@instana/collector/src/tracing/instrumentation/process/childProcess.js
- $HOME/.npm-global/lib/node_modules/@instana/collector/src/tracing/index.js
- $HOME/.npm-global/lib/node_modules/@instana/collector/src/index.js
- /tmp/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ($HOME/.npm-global/lib/node_modules/@instana/collector/src/tracing/instrumentation/process/childProcess.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '$HOME/.npm-global/lib/node_modules/@instana/collector/src/tracing/instrumentation/process/childProcess.js',
    '$HOME/.npm-global/lib/node_modules/@instana/collector/src/tracing/index.js',
    '$HOME/.npm-global/lib/node_modules/@instana/collector/src/index.js',
    '/tmp/[eval]'
  ]
}
```

Apparently `@instana/collector/src/tracing/instrumentation/process/childProcess.js` assumes that `@instana/core` is installed at `../../../../../core` instead of simply letting Node.js resolve it using `@instana/core/[...]`.

**Comment by willianpc** [comment] 2021-04-07 10:52
> 
> Apparently `@instana/collector/src/tracing/instrumentation/process/childProcess.js` assumes that `@instana/core` is installed at `../../../../../core` instead of simply letting Node.js resolve it using `@instana/core/[...]`.

I will take a look. Thanks for the report

**Comment by daka1510** [comment] 2021-04-07 12:29
Thanks for reporting, @michael42. It also broke my application build and I ended up here and was glad I didn't have to troubleshoot it myself.

@willianpc - what countermeasures are taken to make sure that this kind of failures will be noticed before they make it into a future release? Are additional quality gates needed?

As this has shown, many consumers may flow with the latest patch levels and it'd be good to avoid that they have to spend time debugging an instrumentation library when updating e.g. from 1.118.0 -> 1.119.0 :).

**Comment by willianpc** [comment] 2021-04-07 14:12
Hi @daka1510 , I am unable to give you exactly what particular counter measures will be taken, but obviously something will be done.
My first guess is that at least adding a new test in the pipeline must be done, but extra checks may become necessary.

The patch is out. Could you folks please check if the problem is gone?

**Comment by michael42** [comment] 2021-04-08 14:35
Looks fine on my machine, we'll bump the version in our Docker image soon.

**Comment by willianpc** [comment] 2021-04-08 15:08
> Looks fine on my machine, we'll bump the version in our Docker image soon.

@michael42 great. Can you keep me posted? I will keep the issue opened a little longer, just to be sure.

~ Cheers

**Comment by daka1510** [comment] 2021-04-09 11:42
Works in our setup, too. Thanks for the quick turnaround @willianpc.

**Comment by basti1302** [comment] 2021-04-09 19:33
> [...] what countermeasures are taken to make sure that this kind of failures will be noticed before they make it into a future release? Are additional quality gates needed?

Looks like we could add https://github.com/sterlingwes/eslint-plugin-monorepo-cop or something similar to be safe from an oversight like this in the future. We'll look into this soon.

**Comment by basti1302** [comment] 2021-04-12 08:10
For the record: We added the aformentioned rule here: https://github.com/instana/nodejs-sensor/commit/f57c3b8c32dac11c5b1c574c544435510dc7186b.

I'm going ahead and close this one, since it is fixed.

**Closed by basti1302** 2021-04-12 08:10 UTC
